openstack overcloud deploy --templates /usr/share/openstack-tripleo-heat-templates/ \
--disable-validations  \
-e /usr/share/openstack-tripleo-heat-templates/environments/deployed-server-environment.yaml  \
-e /usr/share/openstack-tripleo-heat-templates/environments/deployed-server-bootstrap-environment-rhel.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/deployed-server-pacemaker-environment.yaml  \
-r /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-server-roles-data.yaml  \
-e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
-e /home/stack/templates/network-environment.yaml   \
-e /home/stack/templates/ctlplane-assignments.yaml  \
-e /home/stack/templates/overcloud_images.yaml \
--ntp-server clock.redhat.com
