parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.122.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 10.10.10.200
        start: 10.10.10.100
    ExternalInterfaceDefaultRoute: 10.10.10.1
    ExternalNetCidr: 10.10.10.0/24
    #ExternalNetworkVlanID: 10
    InternalApiAllocationPools:
    -   end: 192.168.124.200
        start: 192.168.124.20
    InternalApiNetCidr: 192.168.124.0/24
    InternalApiNetworkVlanID: 202
    NeutronBridgeMappings: datacentre:br-ex
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: vlan
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 192.168.125.200
        start: 192.168.125.20
    StorageMgmtAllocationPools:
    -   end: 192.168.128.60
        start: 192.168.128.30
    StorageMgmtNetCidr: 192.168.128.0/24
    StorageMgmtNetworkVlanID: 203
    StorageNetCidr: 192.168.125.0/24
    StorageNetworkVlanID: 201
    TenantAllocationPools:
    -   end: 192.168.123.200
        start: 192.168.123.20
    TenantNetCidr: 192.168.123.0/24
    TenantNetworkVlanID: 204
resource_registry:
    #OS::TripleO::BlockStorage::Net::SoftwareConfig: three-nics-vlans/legacy/cinder-storage.yaml
    #OS::TripleO::CephStorage::Net::SoftwareConfig: three-nics-vlans/legacy/ceph-storage.yaml
    OS::TripleO::ComputeDeployedServer::Net::SoftwareConfig: /home/stack/templates/compute0.yaml
    OS::TripleO::ControllerDeployedServer::Net::SoftwareConfig: /home/stack/templates/controller0.yaml
    #OS::TripleO::ObjectStorage::Net::SoftwareConfig: three-nics-vlans/legacy/swift-storage.yaml
